//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Part4.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Part4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на firstname        ///Aaron        ///Aaron        ///Abbey        ///Abbie        ///Abby        ///Abdul        ///Abe        ///Abel        ///Abigail        ///Abraham        ///Abram        ///Ada        ///Adah        ///Adalberto        ///Adaline        ///Adam        ///Adam        ///Adan        ///Addie        ///Adela        ///Adelaida        ///Adelaide        ///Adele        ///Adelia        ///Adelina        ///Adeline        ///Adell        ///Adella        ///Adelle        ///Adena        ///Adina        ///Adolfo        ///Adolph        ///Adria        ///Adrian        ///Adrian        ///Adriana        ///Adriane        ///Adrianna        ///Adrianne        ///Adrien        ///Adriene        ///Adrienne        ///Afton        ///Agatha        ///Agnes        ///Agnus        ///Agripina        ///Agueda        ///Agustin        ///Agustina        ///Ahmad        ///Ahmed        ///Ai        ///Aida        ///Aide        ///Aiko        ///Aileen        ///Ailene        ///Aimee        ///Aisha        ///Aja        ///Akiko        ///Akilah        ///Al        ///Alaina        ///Alaine        ///Alan        ///Alana        ///Alane        ///Alanna        ///Alayna        ///Alba        ///Albert        ///Albert        ///Alberta        ///Alber [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CSV_Database_of_First_Names {
            get {
                return ResourceManager.GetString("CSV_Database_of_First_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lastname        ///Aaberg        ///Aaby        ///Aadland        ///Aagaard        ///Aakre        ///Aaland        ///Aalbers        ///Aalderink        ///Aalund        ///Aamodt        ///Aamot        ///Aanderud        ///Aanenson        ///Aanerud        ///Aarant        ///Aardema        ///Aarestad        ///Aarhus        ///Aaron        ///Aarons        ///Aaronson        ///Aarsvold        ///Aas        ///Aasby        ///Aase        ///Aasen        ///Aavang        ///Abad        ///Abadi        ///Abadie        ///Abair        ///Abaja        ///Abajian        ///Abalos        ///Abaloz        ///Abar        ///Abarca        ///Abare        ///Abascal        ///Abasta        ///Abate        ///Abati        ///Abatiell        ///Abato        ///Abatti        ///Abaunza        ///Abaya        ///Abbadessa        ///Abbamonte        ///Abbas        ///Abbasi        ///Abbassi        ///Abbate        ///Abbatiello        ///Abbay        ///Abbe        ///Abbed        ///Abbenante        ///Abbey        ///Abbinanti        ///Abbington        ///Abbitt        ///Abbot        ///Abbott        ///Abboud        ///Abbruzzese        ///Abbs        ///Abby        ///Abdalla        ///Abdalla [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CSV_Database_of_Last_Names {
            get {
                return ResourceManager.GetString("CSV_Database_of_Last_Names", resourceCulture);
            }
        }
    }
}
